# Summarisation Configuration

# Chunking settings
chunking:
  # Maximum size of each chunk in characters
  max_chunk_size: 1000
  # Amount of overlap between chunks in characters
  chunk_overlap: 100

# Extraction settings
extraction:
  # Extraction percentages for chunk-based extraction
  percentages:
    - 0.34  # First chunk
    - 0.30  # Second chunk
    - 0.245 # Third chunk
    - 0.20  # Fourth chunk
    - 0.165 # Fifth chunk
  default_percentage: 0.125  # For chunks beyond the fifth

# Summary length settings by document size
tier1:  # 0-600 words
  thresholds:
    short: 150
    medium: 300
  summary_ranges:
    short: [15, 50]
    medium: [50, 100]
    long: [100, 200]

tier2:  # 600-2,500 words
  extraction:
    min: 300
    max: 600
    ratio: 0.3
  summary_multiplier:
    min: 0.6
    max: 0.8

tier3:  # 2,500-20,000 words
  final_extraction_target: 1500
  final_abstractive:
    min: 480
    max: 600

tier4:  # 20,000-68,000 words
  final_extraction_target: 2500
  final_abstractive:
    min: 600
    max: 800
