scraping:
  base_url: 'https://eur-lex.europa.eu'
  request_timeout: 30
  language: 'EN'

storage:
  base_dir: 'data'
  file_format: 'json'

metrics:
  enabled: true
  directory: 'metrics'  # Directory to store metrics files
  export_port: null  # Disable HTTP export

logging:
  level: 'DEBUG'  # Set to DEBUG for more information
  format: '<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>'
  rotation: '100 MB'  # Rotate log files when they reach 100MB
  retention: '30 days'  # Keep log files for 30 days
